### ISSUE TITLE
blinksocks不支持用systemd运行吗？?

### ISSUE THREAD

**Issue by luckypoem** [blinksocks/blinksocks#102]
blinksocks --config blinksocks.server.json是在前台运行的，我 想使用systemd来把blinksocks --config blinksocks.server.json运行为service:
nano /etc/systemd/system/blinksocks.service

其内容为：
[Unit]
Description=blinksocks
After=network.target

[Service]
ExecStart=/root/node-v9.8.0-linux-x64/bin/blinksocks --config /root/blinksocks.server.json
Restart=always

[Install]
WantedBy=multi-user.target

我尝试启动blinksocks：
systemctl daemon-reload 

systemctl start blinksocks

这其实就是以daemon(service)方式启动blinksocks程序。
我以为blinksocks已经在后台运行了，但是:
root@ar:~#  ps aux|grep blinksocks
root      9159  0.0  0.0  11072   820 pts/6    S+   05:56   0:00 grep blinksocks
root@ar:~#
这说明blinksocks其实未在运行中。这是为什么？难道blinksocks不支持用systemd运行吗？?

* **Please tell us about your environment:**
- blinksocks version: 3.1.0
- Node.js version: 9.8.0
- npm version: 5.6.0
- os:  Debian GNU/Linux 8

root@ar:~# blinksocks --version
3.1.0
root@ar:~# node --version
v9.8.0
root@ar:~# npm --version
5.6.0
root@ar:~# cat /etc/issue.net
Debian GNU/Linux 8
root@ar:~#

**Comment by micooz** [comment]
`/root/node-v9.8.0-linux-x64/bin/blinksocks` 这个路径是否正确？

**Comment by luckypoem** [comment]
hi.
运行journalctl -u blinksocks.service后，输出：
Mar 18 05:18:19 ar systemd[1]: Starting blinksocks...
Mar 18 05:18:19 ar systemd[1]: Started blinksocks.
Mar 18 05:18:19 ar systemd[1]: blinksocks.service: main process exited, code=exited, status=127/n/a
Mar 18 05:18:19 ar systemd[1]: Unit blinksocks.service entered failed state.
Mar 18 05:18:19 ar blinksocks[8883]: /usr/bin/env: node: No such file or directory
Mar 18 05:18:19 ar systemd[1]: blinksocks.service holdoff time over, scheduling restart.
Mar 18 05:18:19 ar systemd[1]: Stopping blinksocks...
Mar 18 05:18:19 ar systemd[1]: Starting blinksocks...
Mar 18 05:18:19 ar systemd[1]: Started blinksocks.
Mar 18 05:18:19 ar blinksocks[8885]: /usr/bin/env: node: No such file or directory
Mar 18 05:18:19 ar systemd[1]: blinksocks.service: main process exited, code=exited, status=127/n/a
Mar 18 05:18:19 ar systemd[1]: Unit blinksocks.service entered failed state.
Mar 18 05:18:19 ar systemd[1]: blinksocks.service holdoff time over, scheduling restart.
Mar 18 05:18:19 ar systemd[1]: Stopping blinksocks...
Mar 18 05:18:19 ar systemd[1]: Starting blinksocks...
Mar 18 05:18:19 ar systemd[1]: Started blinksocks.
Mar 18 05:18:19 ar blinksocks[8887]: /usr/bin/env: node: No such file or directory
Mar 18 05:18:19 ar systemd[1]: blinksocks.service: main process exited, code=exited, status=127/n/a
Mar 18 05:18:19 ar systemd[1]: Unit blinksocks.service entered failed state.
Mar 18 05:18:19 ar systemd[1]: blinksocks.service holdoff time over, scheduling restart.
Mar 18 05:18:19 ar systemd[1]: Stopping blinksocks...
Mar 18 05:18:19 ar systemd[1]: Starting blinksocks...
Mar 18 05:18:19 ar systemd[1]: blinksocks.service start request repeated too quickly, refusing to start.
Mar 18 05:18:19 ar systemd[1]: Failed to start blinksocks.
Mar 18 05:18:19 ar systemd[1]: Unit blinksocks.service entered failed state.
Mar 18 05:20:06 ar systemd[1]: Starting blinksocks...
Mar 18 05:20:06 ar systemd[1]: Started blinksocks.
Mar 18 05:20:06 ar blinksocks[8903]: /usr/bin/env: node: No such file or directory
Mar 18 05:20:06 ar systemd[1]: blinksocks.service: main process exited, code=exited, status=127/n/a
Mar 18 05:20:06 ar systemd[1]: Unit blinksocks.service entered failed state.
Mar 18 05:20:06 ar systemd[1]: blinksocks.service holdoff time over, scheduling restart.
Mar 18 05:20:06 ar systemd[1]: Stopping blinksocks...
Mar 18 05:20:06 ar systemd[1]: Starting blinksocks...
Mar 18 05:20:06 ar systemd[1]: Started blinksocks.
Mar 18 05:20:06 ar blinksocks[8905]: /usr/bin/env: node: No such file or directory
Mar 18 05:20:06 ar systemd[1]: blinksocks.service: main process exited, code=exited, status=127/n/a
Mar 18 05:20:06 ar systemd[1]: Unit blinksocks.service entered failed state.
Mar 18 05:20:06 ar systemd[1]: blinksocks.service holdoff time over, scheduling restart.

root@ar:~# /usr/bin/env
TERM=xterm-256color
SHELL=/bin/bash
SSH_CLIENT=223.74.103.246 12633 20710
SSH_TTY=/dev/pts/0
USER=root
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/node-v9.8.0-linux-x64/bin
PWD=/root
SHLVL=1
HOME=/root
LOGNAME=root
SSH_CONNECTION=223.74.103.246 12633 104.223.56.178 20710
_=/usr/bin/env
root@ar:~#

上面的“/usr/bin/env: node: No such file or directory”是什么意思？

root@ar:~# which  blinksocks
/root/node-v9.8.0-linux-x64/bin/blinksocks
root@ar:~#
所以
/root/node-v9.8.0-linux-x64/bin/blinksocks这个路径是正确的。

**Comment by Indexyz** [comment]
你的 nodejs路径 不在 `PATH` 环境变量中

**Comment by luckypoem** [comment]
所以不明白“/usr/bin/env: node: No such file or directory”是什么意思。

**Comment by micooz** [comment]
贴一下 `$ which node` 的输出。

**Comment by Indexyz** [comment]
是不是将 PATH 的设定加入到了 bashrc 等文件中而不是对全局生效
如果是的话可以尝试下 在 systemd 的 service 中设定 设置 PATH
```
[Service]
Environment="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/node-v9.8.0-linux-x64/bin"
```
“/usr/bin/env: node: No such file or directory” 的意思是未在 PATH 中找到 node
或者可以尝试将 node alias 到 /usr/bin 中
```
ln -s /root/node-v9.8.0-linux-x64/bin/node /usr/bin/node
```

**Comment by luckypoem** [comment]
@Indexyz 
在 systemd 的 service 中加入了Environment那一项也不行。不过，
将 node alias 到 /usr/bin 中：
ln -s /root/node-v9.8.0-linux-x64/bin/node /usr/bin/node
然后就ok了：
root@ar:~# ln -s /root/node-v9.8.0-linux-x64/bin/node /usr/bin/node
root@ar:~# systemctl start blinksocks
root@ar:~# ps aux|grep blinksocks
root      9511 15.0  3.0 1018788 32304 ?       Ssl  09:20   0:00 node /root/node-v9.8.0-linux-x64/bin/blinksocks --config /root/blinksocks.server.json
root      9522  0.0  0.0  11072   816 pts/4    S+   09:20   0:00 grep blinksocks
root@ar:~# 
谢谢
