### ISSUE TITLE
这个可以用在服务器那边是 shadowsocks 吗

### ISSUE THREAD

**Issue by crapthings** [blinksocks/blinksocks#21]

**Comment by micooz** [comment]
Not compatible with `shadowsocks` at present. `shadowsocks-client` is recommended for servers who deployed the `shadowsocks-server`.

No presets are suitable for `shadowsocks` server. But we can implement some later.

**Comment by micooz** [comment]
Now blinksocks should be worked well with shadowsocks `stream ciphers`:

```js
// available ciphers
const ciphers = [
  // both supported
  'aes-128-ctr', 'aes-192-ctr', 'aes-256-ctr',
  'aes-128-cfb', 'aes-192-cfb', 'aes-256-cfb',
  'camellia-128-cfb', 'camellia-192-cfb', 'camellia-256-cfb',
  // blinksocks supported
  'aes-128-ofb', 'aes-192-ofb', 'aes-256-ofb',
  'aes-128-cbc', 'aes-192-cbc', 'aes-256-cbc'
];
```

The new `AEAD ciphers` will be added to blinksocks later.

* https://github.com/blinksocks/blinksocks#work-with-shadowsocks
* https://shadowsocks.org/en/spec/Stream-Ciphers.html
* https://shadowsocks.org/en/spec/AEAD-Ciphers.html

**Comment by micooz** [comment]
Also see #27 for implementation progress.
