### ISSUE TITLE
可以自动切换服务器吗？

### ISSUE THREAD

**Issue by crapthings** [blinksocks/blinksocks#22]

**Comment by crapthings** [comment]
或者程序上使用这个模块
简单自己判断一下服务器情况，把具体服务器再给这个模块。

**Comment by micooz** [comment]
Cannot figure it out what are you means?

**Comment by crapthings** [comment]
我有一堆服务器列表，我想知道哪个可以用，哪个延迟相对低一些

**Comment by micooz** [comment]
Not support multiple servers mode. But this is a nice feature, I will put it in the plan.
