### ISSUE TITLE
Support for chacha20-ietf and chacha20-ietf-poly1305

### ISSUE THREAD

**Issue by micooz** [blinksocks/blinksocks#43]
Those two ciphers are not currently implemented in **openssl**, but we can make use of [libsodium](https://libsodium.org/).

The js bindings such as [libsodium.js](https://github.com/jedisct1/libsodium.js) or [js-nacl](https://github.com/tonyg/js-nacl) maybe too huge/verbose for blinksocks.

[Node.js C/C++ Addons](https://nodejs.org/dist/latest-v6.x/docs/api/addons.html) is a better way to integrate libsodium.

**Comment by acgtyrant** [comment]
wontfix? So AEAD Ciphers can use only aes-*-gcm now?

**Comment by micooz** [comment]
@acgtyrant 

Several consideration:

* Integrate libsodium is currently hard in Node.js. It requires external build process(not system-wide) after install.
* Third-party libraries are not platform-friendly because the main goal of blinksocks is to be a pure 
 framework.
* Crypto module is only used in presets which are independent of each other, so chacha20-* are not required by blinksocks itself.
* AES is strong as well as fast enough for most cases.

I leave this stuff to users/developers who can reform blinksocks for their own needs.
